FROM jupyter/datascience-notebook

RUN conda install --quiet --yes \
    -c conda-forge root &&\
    conda clean --all -f -y && \
    fix-permissions $CONDA_DIR

RUN mv /home/jovyan/work /home/jovyan/persistent-storage
CMD ["jupyter", "lab"]